# You can use, for example, the following command to build the intermediate image:
# docker build -f Dockerfile-r-base-tidyverse -t toivoja/r-base-tidyverse .

# Base image https://hub.docker.com/u/rocker/
#FROM rocker/r-base:latest
#FROM rocker/r-base:3.6.3
#FROM rocker/r-ubuntu:18.04
FROM rocker/r-ubuntu:20.04

## install debian packages needed for tidyverse
#RUN add-apt-repository -y "ppa:marutter/rrutter3.5"
#RUN add-apt-repository -y -y "ppa:marutter/c2d4u3.5"
RUN apt-get update -qq && apt-get -y --no-install-recommends install \
#libv8-dev \
libxml2-dev \
libcairo2-dev \
libsqlite3-dev \
libmariadbd-dev \
libpq-dev \
libssh2-1-dev \
unixodbc-dev \
libcurl4-openssl-dev \
libssl-dev \
pandoc \
texlive-latex-base \
texlive-latex-recommended \
texlive-fonts-recommended \
texlive-latex-extra \
lmodern

RUN apt-get update -qq && apt-get -y --no-install-recommends install \
r-cran-bh \
r-cran-rstan \
r-cran-v8 \
r-cran-brms \
r-cran-e1071 \
r-cran-tidyverse \
r-cran-magrittr \
r-cran-knitr

RUN apt-get update -qq && apt-get -y --no-install-recommends install \
r-cran-rook \
r-cran-plumber \
r-cran-rocr \
r-cran-furrr \
r-cran-tictoc \
r-cran-caret \
r-cran-entropy \
r-cran-ggmcmc \
r-cran-ggthemes \
r-cran-proc \
r-cran-ranger \
r-cran-rjson \
r-cran-kernlab

RUN apt-get update -qq && apt-get -y --no-install-recommends install \
r-cran-sn \
r-cran-slider \
r-cran-cowplot \
r-cran-gridextra \
r-cran-desctools \
r-cran-bayestestr 
#r-cran-cutpointr  # not available in binary

RUN apt-get -y --no-install-recommends install time

## copy files
COPY src/docker-create-r-toolchain.R /docker-create-r-toolchain.R
COPY src/docker-install-packages2.R /docker-install-packages2.R

## install R-packages
RUN Rscript /docker-create-r-toolchain.R   # this is for rstan
RUN Rscript /docker-install-packages2.R
