# Create the application image using the following command:
# docker build -t toivoja/hb-predictor .

FROM toivoja/r-base-tidyverse:latest

## create directories
#RUN mkdir -p /01_data
RUN mkdir -p /src
RUN mkdir -p /output

## copy files
COPY /src/docker-server-rook.R /src/docker-server-rook.R

## run the script
CMD Rscript /src/docker-server-rook.R
