install.packages("cutpointr")
install.packages("farver")
install.packages("PRROC")
install.packages("future")
#install.packages("shapper")
install.packages("DALEX")
#install.packages("shapr")
install.packages("fastshap")
install.packages("themis")
#install.packages("tictoc")
#install.packages("entropy")
#install.packages("ggmcmc")
#install.packages("slider")
#devtools::install_github("https://github.com/jttoivon/caret", subdir="pkg/caret", ref="harmonize_ranger_rf_hyperparams")
install.packages("caret")
