---
#title: "Subset analyses"
output: md_document
params:
  input_file: "~/FRCBS/interval_prediction/data/full_data_preprocessed-2020-05-25-train.rdata"
  #input_file: "~/preprocessed_data_6243aede7.rdata"
  hlen: NULL
  hlen_exactly: FALSE
  sample_fraction: 1.0
  method: "both"
  gender: "both"
  id: NULL
  # sample_fraction: 0.004
  # method: "icp-fix"
  # gender: "male"
  # id:   date-2020-07-17-gender-male-method-icp-fix-sample_fraction-0.004
  date: "2020-07-08"
  extra_id: NULL
  summary_table_file: NULL
  effect_size_table_file: NULL
  Hb_cutoff_male: 135
  Hb_cutoff_female: 125
  predictive_variables: NULL
  cores: 4
  iterations: 2000
  skip_train: FALSE
  create_datasets_bool: TRUE
#  donor_specific_file: "~/FRCBS/interval_prediction/data/finngen_snip_prs-2020-07-29.rdata"
  donor_specific_file: NULL
---

```{r, echo=FALSE, message=FALSE}
message(sprintf(">>>>>>>>>> LMMs %s %s >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>", params$gender, knitr::opts_chunk$get("dev")))
```

  
```{r, results="asis", echo=FALSE}
cat(sprintf("# Linear mixed models (%s)\n", params$gender))
```

<!--
<h2> Introduction </h2>

Here I will run analyses for three different models with varying parameters. Each model is run with and without icp-fix and separately for male and female donors resulting in 12 analyses in total. The models are following:

*1.* Linear mixed effect model with random intercept for each donor. Stan-code is in file 'mem_qr_1.stan':

\[
y_{it} = \alpha + b_i + \beta' x_{it} + \epsilon
\]

where $\epsilon \sim N(0, \sigma_{\epsilon}^2), \quad b_i \sim N(0,\sigma_{b}^2)$

*2.* Linear mixed effect model with random intercept for each donor and a random slope for age variable:

\[
y_{it} = \alpha + b_{0i} + (b_{1i} + \beta_0)x_{age,it} + \beta_1' x_{1it} + \epsilon
\]

where $\epsilon \sim N(0, \sigma_{\epsilon}^2), \quad b_{0i}, b_{1i} \sim N(0,\sigma_{b}^2)$

*3.* Linear mixed effect model with random intercept for each donor and a random slope for days_to_previous_fb variable:

\[
y_{it} = \alpha + b_{0i} + (b_{1i} + \beta_0)x_{dtp,it} + \beta_1' x_{1it} + \epsilon
\]

where $\epsilon \sim N(0, \sigma_{\epsilon}^2), \quad b_{0i}, b_{1i} \sim N(0,\sigma_{b}^2)$

The Wooldridge intial conditions problem fix replaces the individual random intercept term $b_i$ with the following term:

\[
b_i = \zeta_0 + \zeta_1 y_{0i} + \upsilon' z_{0i} + a_i
\]

where $a_i \sim N(0,\sigma_a^2)$ and $z$ are exogenous variables that could be associated with the initial observation. Some other variants of Wooldridge solution use the mean of exogenous variables or associate means of other covariates into the model. In this solution $a_i$ is our new random intercept term which is assumed to be uncorrelated with the initial observations $y_{0i}$ satisfying the model assumptions.

The goal of this document is to get a feeling which model seems to work best for our data. This can be used to decide which models should be run on the whole dataset. We can see does the slope variable in models 2 and 3 improve the predictions and if the ICP-fix is suitable for the analyses.

-->

```{r, echo=FALSE}
suppressPackageStartupMessages(library(tidyverse))
```

```{r Descriptions, echo = FALSE}

source("common.R")

```

<!-- <h2> Initialization </h2> -->
```{r Setup, setup = TRUE, echo=FALSE, message=FALSE}

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
library(rstan)
suppressPackageStartupMessages(library(caret))
suppressPackageStartupMessages(library(tictoc))
suppressPackageStartupMessages(library(entropy))
suppressPackageStartupMessages(library(brms))
suppressPackageStartupMessages(library(ggmcmc))
suppressPackageStartupMessages(library(ggthemes))
suppressPackageStartupMessages(library(ggridges))
suppressPackageStartupMessages(library(ROCR))
suppressPackageStartupMessages(library(pROC))
suppressPackageStartupMessages(library(furrr))
suppressPackageStartupMessages(library(sn))
library(tidyselect)

# This can measure time a chunk took to execute.
# Add chunk option time_it=TRUE to each chunk your want to measure.
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      # record the current time before each chunk
      now <<- lubridate::now()
    } else {
      # calculate the time difference after a chunk
      res <- lubridate::now() - now
      # return a character string to show the time
      msg <- paste("Time for this code chunk to run:", as.numeric(res), units(res))
      message(msg)
      NULL   # Don't return the message so that it won't be printed to the resulting document.
    }
  }
}))


knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, time_it=TRUE)
#knitr::opts_chunk$set(echo=TRUE, message=TRUE)
#options(warn = 1)


message("Parameters are:")
for (name in names(params)) {
  message(sprintf("%s = ", name), params[[name]])
}

if (knitr::opts_chunk$get("dev") == "pdf") {
  knitr::opts_chunk$set(dev="cairo_pdf")
  knitr::opts_current$set(dev="cairo_pdf")
}
message(paste0("Device is ", knitr::opts_chunk$get("dev"), "\n"))
message(paste0("Current device is ", knitr::opts_current$get("dev"), "\n"))
use_pdf <- knitr::opts_chunk$get("dev") %in% c("pdf", "cairo_pdf")

# These are used to select which computations to perform,
# base on params$gender and params$method
compute_male   <- params$gender %in% c("male", "both")
compute_female <- params$gender %in% c("female", "both")
compute_nofix  <- params$method %in% c("no-fix", "both")
compute_icpfix <- params$method %in% c("icp-fix", "both")
compute_male_nofix <- compute_male && compute_nofix 
compute_female_nofix <- compute_female && compute_nofix 
compute_male_icpfix <- compute_male && compute_icpfix 
compute_female_icpfix <- compute_female && compute_icpfix 

set.seed(123)
number_of_cores <- parallel::detectCores()
if (!is.null(params$cores)) {
  options(mc.cores = min(4, params$cores, number_of_cores))  # Only four chains used by stan by default
  options(boot.ncpus = min(params$cores, number_of_cores))   # For bootstrapping
} else {
  options(mc.cores = min(4, number_of_cores))  # Only four chains used by stan by default
  options(boot.ncpus = number_of_cores)
}
rstan_options(auto_write = TRUE)

# Set variables to save time knitting the document
#skip_train = params$skip_train
skip_train = use_pdf
#create_datasets_bool = params$create_datasets_bool
create_datasets_bool = ! use_pdf
knit = TRUE

datadir = "../data/rdata/"
dumpdir = "../data/rdump/"
stanfitpath = "../data/stan_fits/"
rawresultdir = "../data/raw_results/"

if (is.null(params$id)) {
  id <- paste(params$date, params$sample_fraction, params$hlen, params$hlen_exactly, params$extra_id, sep="_") 
} else {
  id <- params$id
}
data_id <- id

fit_id = id


source("helper_functions.R")
source("validate_stan_fit.R")
#source("ppc.R")
```

```{r Load datas, echo=FALSE, message=FALSE}

data <- load_single(params$input_file) # Forgets the name of the object

data <- data %>%
  mutate(days_to_previous_fb = as.double(days_to_previous_fb),
         donor = as.character(donor))   # For some reason this cannot be a factor

#variables_to_log <- c("days_to_previous_fb",
#                                "consecutive_deferrals", "recent_donations",
#                                "recent_deferrals")

#data <- data %>%
#  mutate_at(variables_to_log, function(x) log(x+1))

sample_fraction <- params$sample_fraction

is.wholenumber <- function(x, tol = .Machine$double.eps^0.5)  abs(x - round(x)) < tol

if (sample_fraction > 1 && is.wholenumber(sample_fraction)) {  # If instead of fraction a sample size is given, convert it to sample fraction
  low_limit <- ifelse(params$method=="no-fix", 2, 1)
  data <- data %>% group_by(donor) %>%
    filter(n() > low_limit) %>%
    ungroup()
  
  if (params$gender == "male") {
    temp <- data %>% filter(gender=="Men")
  }
  else if (params$gender == "female") {
    temp <- data %>% filter(gender=="Women")
  } else {
    temp <- data
  }
  n <- length(unique(temp$donor))  # number of donors
  rm(temp)
  sample_fraction <- sample_fraction / n
  message(sprintf("Number of donors: %i, sample_fraction: %f", n, sample_fraction))
}

if (!is.null(params$donor_specific_file) && (length(params$donor_specific_file) > 0)) {
  #donor_variables <- c("smoking", "bmi", "RNF43_mutant", "prs")
  #donor_variables <- c("smoking", "height", "weight", "RNF43_mutant", "prs")
  #pretty_donor_variables <- c("Smoking", "Height", "Weight", "RNF43 mutant", "Polygenic risk score")
  findonor_and_snip_and_prs <- load_single(params$donor_specific_file)
  if ("FERRITIN_LAST_DATE" %in% names(findonor_and_snip_and_prs))   # This variable is only included to be able to filter data in random_forest.Rmd
    findonor_and_snip_and_prs <- findonor_and_snip_and_prs %>% select(-FERRITIN_LAST_DATE)
  donor_descript <- donor_descript %>% filter(Variable %in% names(findonor_and_snip_and_prs))
  donor_variables <- donor_descript$Variable
  pretty_donor_variables <- donor_descript$Pretty
  
  
  data <- inner_join(data, findonor_and_snip_and_prs, by="donor")
} else {
  donor_variables = NULL
}

#basic_prediction_variables <- setdiff(descript$Variable, c("donor", "Hb", "Hb_deferral")) 
# Modify this if you want to use a subset of variables for predicting
#basic_prediction_variables <- setdiff(basic_prediction_variables, c("previous_Hb_def", "consecutive_deferrals", "recent_deferrals"))
basic_prediction_variables <- params$predictive_variables

basic_variables <- setdiff(basic_prediction_variables, "previous_Hb")
basic_variables_icp <- setdiff(basic_prediction_variables, "Hb_first")

# Pretty names for parameters
pretty_variables <- descript %>% filter(Variable %in% basic_variables) %>% pull(Pretty)   # Convert to pretty names
pretty_variables_icp <- descript %>% filter(Variable %in%  basic_variables_icp) %>% pull(Pretty)   # Convert to pretty names
first_variables <- c("First age", "First year", "First warm season", "First hour")
#pretty_variables <- basic_vars
pretty_variables_icp <- c(pretty_variables_icp, first_variables)
if (!is.null(donor_variables)) {
  pretty_variables     <- c(pretty_variables, pretty_donor_variables)
  pretty_variables_icp <- c(pretty_variables_icp, pretty_donor_variables)
}

# Stan parameter names
stan_parameters <- sprintf("beta[%i]", 1:length(basic_variables))
stan_parameters_icp <- c(stan_parameters,
               sprintf("ups[%i]", 1:length(first_variables)))
if (!is.null(donor_variables)) {
  donor_pars <- sprintf("phi[%i]", 1:length(donor_variables))
  stan_parameters <- c(stan_parameters, donor_pars)
  stan_parameters_icp <- c(stan_parameters_icp, donor_pars)
}

# Make sure the columns in data are in the same order as in the descript table (and in the vars and pars lists)
variables_in_order <- setdiff(descript$Variable, "donor")
if (!is.null(donor_variables)) {
  data <- data %>% select(all_of(variables_in_order),
                          all_of(donor_variables), everything())
} else {
  data <- data %>% select(all_of(variables_in_order), everything())
}

if (create_datasets_bool) {
  source("jarkko_create_datasets.R")
  lst <- create_datasets(data, datadir, dumpdir, data_id, sample_fraction, hlen=params$hlen, params$hlen_exactly,
                         Hb_cutoff_male = params$Hb_cutoff_male,
                         Hb_cutoff_female = params$Hb_cutoff_female, 
                         basic_variables=basic_variables, basic_variables_icp=basic_variables_icp, donor_variables=donor_variables,
                         compute_male_nofix, compute_female_nofix, compute_male_icpfix, compute_female_icpfix)
  
  data.male <- lst$small.data.male
  data.female <- lst$small.data.female
} else {   # This is only for plotting purpose
  data.male <- data %>% filter(gender == "Men")
  data.female <- data %>% filter(gender == "Women")
  
  # Split for men and women separately
  data.male <- split_set(data.male, 1.0)
  data.female <- split_set(data.female, 1.0)
  names(data.male) <- c("general","validation")
  names(data.female) <- c("general","validation")
  # Small test sets
  smallm <- split_set(data.male$general, sample_fraction)
  smallf <- split_set(data.female$general, sample_fraction)
  data.male <- smallm$train
  data.female <- smallf$train
}

# This in only for plotting purpose
data.male <- filter_based_on_number_of_donations(data.male, params$hlen, params$hlen_exactly)
data.female <- filter_based_on_number_of_donations(data.female, params$hlen, params$hlen_exactly)


if (is.null(donor_variables)) {
  stanf1     <- "stan/container.stan"
  stanf1.icp <- "stan/container_heckman.stan"
} else {
  stanf1     <- "stan/container_consts.stan"
  stanf1.icp <- "stan/container_heckman_consts.stan"
}


summary_rows <- list()  # This is used to construct the error table in the end
                   # It has columns Model, MAE, RMSE
effect_size_rows <- list() # This is for the effect sizes
```



## Data description



### Variables used in prediction

```{r, echo=FALSE}
kable(descript)
kable(donor_descript)
```


```{asis, echo=compute_male}
### Summary plots of variables (male)
```

```{r}

```

```{r Summary plots for males, echo = FALSE, eval=compute_male}
#Plot distributions for male donors

color = "blue"

convert_to_integer <- c("Hb_deferral", "warm_season", "previous_Hb_def")
temp_donors <- data.male$donor

pmale <- data.male %>%
  filter(first_event == FALSE) %>%
  select(all_of(descript$Variable))
  #mutate(across(convert_to_integer, as.integer))

pmale <- summary_plotter(pmale, descript, color)  
pmale

if (!is.null(params$donor_specific_file)) {
  #convert_to_integer <- intersect(c("smoking", "RNF43_mutant"), names(findonor_and_snip_and_prs))
  pmale2 <- findonor_and_snip_and_prs %>%
    filter(donor %in% temp_donors) # %>%
    #mutate(across(convert_to_integer, as.integer)) %>%
  pmale2 <- summary_plotter(pmale2, donor_descript, color)
  pmale2
}

time_series_length_plotter(data.male, color)
  
rm(data.male2);
```



```{asis, echo=compute_female}
### Summary plots of variables (female)
```

```{r Summary plots for females, echo = FALSE, eval=compute_female}
#Plot distributions for female donors

color = "orange"

temp_donors <- data.female$donor

convert_to_integer <- c("Hb_deferral", "warm_season", "previous_Hb_def")
pfemale <- data.female %>%
  filter(first_event == FALSE) %>%
  select(all_of(descript$Variable)) #%>%
  #mutate(across(convert_to_integer, as.integer))

pfemale <- summary_plotter(pfemale, descript, color)
pfemale

# pfemale <- data.female2 %>%
#           keep(is.numeric) %>%
#           to_pretty(descript) %>%
#           gather() %>%
#           mutate(key = factor(key, levels=descript$Pretty))  %>% # Don't sort alphabetically
#           ggplot(aes(value)) +
#             facet_wrap(~ key, scales = "free") +
#             geom_histogram(fill = "orange")


if (!is.null(params$donor_specific_file)) {
  #convert_to_integer <- intersect(c("smoking", "RNF43_mutant"), names(findonor_and_snip_and_prs))
  pfemale2 <- findonor_and_snip_and_prs %>%
    filter(donor %in% temp_donors) #%>%
  pfemale2 <- summary_plotter(pfemale2, donor_descript, color)
    #mutate_at(vars(convert_to_integer), as.integer)
  # pfemale2 <- female_donor_specific %>%
  #   keep(is.numeric) %>%
  #   to_pretty(donor_descript) %>%
  #   gather() %>%
  #   mutate(key = factor(key, levels=donor_descript$Pretty))  %>% # Don't sort alphabetically
  #   ggplot(aes(value)) +
  #   facet_wrap(~ key, scales = "free") +
  #   geom_histogram(fill = "orange")
  pfemale2
}
time_series_length_plotter(data.female, color)

rm(data.female2);
```

```{r, results="asis", echo=FALSE}
cat(sprintf("The male set contains %i donations from %i donors.", nrow(data.male), n_distinct(data.male$donor)))
cat(sprintf("The female set contains %i donations from %i donors.", nrow(data.female), n_distinct(data.female$donor)))
```

```{r clean up memory, echo = FALSE}
rm(data); invisible(gc())
rm(data.male, data.female); invisible(gc(reset = TRUE))
```





## Results


```{asis, echo=compute_male_nofix}
### Linear mixed model, male donors
```

```{r Model 1 male donors, results="hide", eval=compute_male_nofix}
# Load first datasets
message("0")
load(paste(datadir,"stan_preprocessed_datasets_",data_id,".RData", sep = '')) 
load(paste(datadir,"stan_lists_male_nofix_",data_id,".RData", sep = ''))       
cat("1\n")
message("1")
if (skip_train == TRUE) {
  load(paste(stanfitpath, "small_model1_male_", fit_id, ".RData", sep = ''))
    } else {
  fit <- stan(file = stanf1, 
            data = stan.lists.male.nofix,
            save_warmup = TRUE,
            iter = params$iterations,
            open_progress = TRUE,
            verbose = TRUE,
            control = list(max_treedepth = 12))
  save(fit, file = paste(stanfitpath, "small_model1_male_", fit_id, ".RData", sep = ''))
}

rhats <- bayesplot::rhat(fit)
message(sprintf("Maximum rhat is %f for male non-icp\n", max(rhats)))

original_Hb <- denormalize_vector(stan.preprocessed.male.nofix$y_test, stan.preprocessed.male.nofix$par_means["Hb"], stan.preprocessed.male.nofix$par_sds["Hb"]) 
scores <- get_scores(fit, params$Hb_cutoff_male, stan.preprocessed.male.nofix$par_means[["Hb"]], stan.preprocessed.male.nofix$par_sds[["Hb"]])
test_labels <- ifelse(original_Hb < params$Hb_cutoff_male, 1, 0)

val1.m <- validate_fit(fit, 
                       original_Hb, test_labels, params$Hb_cutoff_male, score=scores,
                       stan_parameters, pretty_variables, metric = "mean", cat.plot = FALSE)
#val1.m

val1.m$posterior.plot
val1.m$scatter_plot
val1.m$confusion.matrix.plot
val1.m$roc_plot
val1.m$pr_plot

t <- tibble(Id="male-lmm", Model="Linear mixed model", Gender=params$gender, 
            MAE=val1.m$mae, RMSE=val1.m$rmse, 
            MAE2=val1.m$mae2, RMSE2=val1.m$rmse2)
t <- bind_cols(c(t, val1.m$roc_ci, val1.m$pr_ci, val1.m$f1_ci))
summary_rows[[length(summary_rows)+1]] <- t
effect_size_rows[[length(effect_size_rows)+1]] <- val1.m$posterior.plot$cis %>% mutate(Id="male-lmm")

save(val1.m, file = paste(rawresultdir, "raw_result_male_", fit_id, ".rdata", sep = ''))

# Remove unnescessary values to save memory
if (knit == TRUE) {rm(stan.lists.male.nofix, val1.m, fit); invisible(gc(reset = TRUE))}

```


```{asis, echo=compute_female_nofix}
### Linear mixed model, female donors
```

```{r Model 1 female donors, results="hide", eval=compute_female_nofix}
if (!exists("stan.preprocessed.female.nofix"))
  load(paste(datadir,"stan_preprocessed_datasets_",data_id,".RData", sep = ''))
if (!exists("stan.lists.female.nofix"))
  load(paste(datadir,"stan_lists_female_nofix_",data_id,".RData", sep = ''))
warning("here1")
if (skip_train == TRUE) {
  load(paste(stanfitpath, "small_model1_female_", fit_id, ".RData", sep = ''))
} else {
  fit <- stan(file = stanf1, 
            data = stan.lists.female.nofix,
            save_warmup = TRUE,
            iter = params$iterations,
            control = list(max_treedepth = 12))
  save(fit, file = paste(stanfitpath, "small_model1_female_", fit_id, ".RData", sep = ''))
}

rhats <- rhat(fit)
message(sprintf("Maximum rhat is %f for female non-icp\n", max(rhats)))



original_Hb <- denormalize_vector(stan.preprocessed.female.nofix$y_test, stan.preprocessed.female.nofix$par_means["Hb"], stan.preprocessed.female.nofix$par_sds["Hb"]) 
scores <- get_scores(fit, params$Hb_cutoff_female, stan.preprocessed.female.nofix$par_means[["Hb"]], stan.preprocessed.female.nofix$par_sds[["Hb"]])
test_labels <- ifelse(original_Hb >= params$Hb_cutoff_female, 0, 1)

val1.f <- validate_fit(fit,  
                       original_Hb, test_labels, params$Hb_cutoff_female, scores,
                       stan_parameters, pretty_variables, metric = "mean", cat.plot = FALSE)

val1.f$posterior.plot
val1.f$scatter_plot
val1.f$confusion.matrix.plot
val1.f$roc_plot
val1.f$pr_plot

t <- tibble(Id="female-lmm", Model="Linear mixed model", Gender=params$gender, 
            MAE=val1.f$mae, RMSE=val1.f$rmse, 
            MAE2=val1.f$mae2, RMSE2=val1.f$rmse2)
t <- bind_cols(c(t, val1.f$roc_ci, val1.f$pr_ci, val1.f$f1_ci))
summary_rows[[length(summary_rows)+1]] <- t
effect_size_rows[[length(effect_size_rows)+1]] <- val1.f$posterior.plot$cis %>% mutate(Id="female-lmm")

save(val1.f, file = paste(rawresultdir, "raw_result_female_", fit_id, ".rdata", sep = ''))

if (knit == TRUE) {rm(stan.lists.female.nofix, val1.f, fit); invisible(gc(reset = TRUE))}

```


```{asis, echo=compute_male_icpfix}
### Dynamic linear mixed model, male donors
```

```{r Model 1 male donors icp-fix, results="hide", eval=compute_male_icpfix}
message("heipparallaa")
if (!exists("stan.preprocessed.male.icpfix"))
  load(paste(datadir,"stan_preprocessed_datasets_",data_id,".RData", sep = ''))
if (!exists("stan.lists.male.icpfix"))
  load(paste(datadir,"stan_lists_male_icpfix_",data_id,".RData", sep = ''))
message("taalla ollaan")
if (skip_train == TRUE) {
  load(paste(stanfitpath, "small_model1_male_icp_", fit_id, ".RData", sep = ''))
} else {
  fit <- stan(file = stanf1.icp, 
            data = stan.lists.male.icpfix,
            save_warmup = TRUE,
            iter = params$iterations,
            open_progress = FALSE,
            verbose = TRUE,
            control = list(max_treedepth = 12))
  save(fit, file = paste(stanfitpath, "small_model1_male_icp_", fit_id, ".RData", sep = ''))
}

rhats <- rhat(fit)
message(sprintf("Maximum rhat is %f for male icp\n", max(rhats)))



original_Hb <- denormalize_vector(stan.preprocessed.male.icpfix$y_test, stan.preprocessed.male.icpfix$par_means["Hb"], stan.preprocessed.male.icpfix$par_sds["Hb"]) 
scores <- get_scores(fit, params$Hb_cutoff_male, stan.preprocessed.male.icpfix$par_means[["Hb"]], stan.preprocessed.male.icpfix$par_sds[["Hb"]])
test_labels <- ifelse(original_Hb >= params$Hb_cutoff_male, 0, 1)

val1.m.icp <- validate_fit(fit, 
                           original_Hb, test_labels, params$Hb_cutoff_male, scores,
                           stan_parameters_icp, pretty_variables_icp, metric = "mean", cat.plot = FALSE)

val1.m.icp$posterior.plot
val1.m.icp$scatter_plot
val1.m.icp$confusion.matrix.plot
val1.m.icp$roc_plot
val1.m.icp$pr_plot

t <- tibble(Id="male-dlmm", Model="Dynamic linear mixed model", Gender=params$gender, 
            MAE=val1.m.icp$mae, RMSE=val1.m.icp$rmse, 
                                        MAE2=val1.m.icp$mae2, RMSE2=val1.m.icp$rmse2)
t <- bind_cols(c(t, val1.m.icp$roc_ci, val1.m.icp$pr_ci, val1.m.icp$f1_ci))
summary_rows[[length(summary_rows)+1]] <- t
effect_size_rows[[length(effect_size_rows)+1]] <- val1.m.icp$posterior.plot$cis %>% mutate(Id="male-dlmm")

save(val1.m.icp, file = paste(rawresultdir, "raw_result_male_icp_", fit_id, ".rdata", sep = ''))

if (knit == TRUE) {rm(stan.lists.male.icpfix, val1.m.icp, fit); invisible(gc(reset = TRUE))}

```

```{asis echo=compute_female_icpfix}
### Dynamic linear mixed model, female donors
```

```{r Model 1 female donors icp-fix, results="hide", eval=compute_female_icpfix}
if (!exists("stan.preprocessed.female.icpfix"))
  load(paste(datadir,"stan_preprocessed_datasets_",data_id,".RData", sep = ''))
if (!exists("stan.lists.female.icpfix"))
  load(paste(datadir,"stan_lists_female_icpfix_",data_id,".RData", sep = ''))

if (skip_train == TRUE) {
  load(paste(stanfitpath, "small_model1_female_icp_", fit_id, ".RData", sep = ''))
} else {
  fit <- stan(file = stanf1.icp, 
            data = stan.lists.female.icpfix,
            save_warmup = TRUE,
            iter = params$iterations,
            control = list(max_treedepth = 12))
  save(fit, file = paste(stanfitpath, "small_model1_female_icp_", fit_id, ".RData", sep = ''))
}

rhats <- rhat(fit)
message(sprintf("Maximum rhat is %f for female icp\n", max(rhats)))



original_Hb <- denormalize_vector(stan.preprocessed.female.icpfix$y_test, stan.preprocessed.female.icpfix$par_means["Hb"], stan.preprocessed.female.icpfix$par_sds["Hb"]) 
scores <- get_scores(fit, params$Hb_cutoff_female, stan.preprocessed.female.icpfix$par_means[["Hb"]], stan.preprocessed.female.icpfix$par_sds[["Hb"]])
test_labels <- ifelse(original_Hb >= params$Hb_cutoff_female, 0, 1)

val1.f.icp <- validate_fit(fit, 
                           original_Hb, test_labels, params$Hb_cutoff_female, scores,
                           stan_parameters_icp, pretty_variables_icp, metric = "mean", cat.plot = FALSE)

val1.f.icp$posterior.plot
val1.f.icp$scatter_plot
val1.f.icp$confusion.matrix.plot
val1.f.icp$roc_plot
val1.f.icp$pr_plot

t <- tibble(Id="female-dlmm", Model="Dynamic linear mixed model", Gender=params$gender, 
            MAE=val1.f.icp$mae, RMSE=val1.f.icp$rmse, MAE2=val1.f.icp$mae2, RMSE2=val1.f.icp$rmse2)
t <- bind_cols(c(t, val1.f.icp$roc_ci, val1.f.icp$pr_ci, val1.f.icp$f1_ci))
summary_rows[[length(summary_rows)+1]] <- t
effect_size_rows[[length(effect_size_rows)+1]] <- val1.f.icp$posterior.plot$cis %>% mutate(Id="female-dlmm")

save(val1.f.icp, file = paste(rawresultdir, "raw_result_female_icp_", fit_id, ".rdata", sep = ''))

if (knit == TRUE) {rm(stan.lists.female.icpfix, val1.f.icp, fit); invisible(gc(reset = TRUE))}

```


```{r}
effect_size_table <- bind_rows(effect_size_rows)
if (!is.null(params$effect_size_table_file)) {
  write_csv(effect_size_table, params$effect_size_table_file)   # Pass the table to the web app as well
}
```


### Summary

```{r Errors}

#str(error_rows)
#df <- do.call(rbind, error_rows)
# for (i in seq_along(error_rows)) {
#   if (i == 1) {
#     errors <- as_tibble(error_rows[[1]])
#   } else {
#     errors <- rbind(errors, error_rows[[i]])
#   }
# }
summary_table <- bind_rows(summary_rows)
#errors <- as_tibble(df)
summary_table <- summary_table %>% rename("MAE (g / L)" = MAE, "RMSE (g / L)" = RMSE,
                            "MAE (mmol / L)" = MAE2, "RMSE (mmol / L)" = RMSE2)

write_csv(summary_table, paste(rawresultdir, "errors_", fit_id, ".csv", sep = ''))
if (!is.null(params$summary_table_file)) {
  write_csv(summary_table, params$summary_table_file)   # Pass the table to the web app as well
}

```

```{r}
cols <- c("Model", "Gender", "MAE (g / L)", "RMSE (g / L)", "MAE (mmol / L)", "RMSE (mmol / L)", "AUROC" = "AUROC value", "AUPR" = "AUPR value", "F1" = "F1 value")
kable(summary_table %>% select(!!!cols), digits=3, format.args = list(digits=3))
```




