---
#title: "Subset analyses"
output: md_document
params:
  input_file: "~/FRCBS/interval_prediction/data/full_data_preprocessed-2020-05-25-train.rdata"
  hlen: NULL
  hlen_exactly: FALSE
  sample_fraction: 1.0
  method: "both"
  gender: "both"
  id: NULL
  date: "2020-07-08"
  extra_id: NULL
  errors_table_file: NULL
  Hb_cutoff_male: 135
  Hb_cutoff_female: 125
  cores: 4
  iterations: 2000
  skip_train: FALSE
  create_datasets_bool: TRUE
#  donor_specific_file: "~/FRCBS/interval_prediction/data/finngen_snip_prs-2020-07-29.rdata"
  donor_specific_file: NULL
---

  
```{r, results="asis", echo=FALSE}
cat(sprintf("# Subset analyses (%s)\n", params$gender))
```



```{r, echo=FALSE}
suppressPackageStartupMessages(library(tidyverse))
```

```{r, echo = FALSE}

# Variables that are in use

descript <- tibble(Variable = c("donor", "Hb", "days_to_previous_fb", "age", "previous_Hb_def", 
                                "year", "warm_season", "consecutive_deferrals", "recent_donations",
                                "recent_deferrals", "hour", 
                                "previous_Hb", "Hb_first", "Hb_deferral"), 
                   Pretty = c("Donor ID", "Hemoglobin", "Days to previous full blood donation", "Age", "Previous Hb deferral", 
                              "Year", "Warm season", "Consecutive deferrals", "Recent donations", 
                              "Recent deferrals", "Hour", 
                              "Previous Hb", "First Hb", "Hb deferral"),
                   Type = c("Factor", "numeric", "numeric (int)", "numeric", "boolean",
                            "numeric (int)", "boolean", "numeric (int)", "numeric (int)", "numeric (int)", "numeric",
                            "numeric", "numeric", "boolean"),
                   Explanation = c("Donor identifier",
                                   "Amount of Hemoglobin",
                                   "Time (in days) between Hb measurement and previous full blood donation event",
                                   "Age of donor",
                                   "Indicates whether the donor was deferred from blood donation due to low hemoglobin at previous donation event",
                                   "Year of donation",
                                   "True if donation was given in April-September",
                                   "Number of times the donor has been deferred due to low hemoglobin since last succesful whole blood donation",
                                   "Number of donations in the last two years",
                                   "Number of deferrals due to low hemoglobin in the last two years",
                                   "Time of day when donation was given as hours (e.g. 13:45 = 13.75)",
                                   "Hb value at previous measurement (ICP-model)",
                                   "Hb value at first donation of this donor (Non ICP-model)",
                                   "Deferred based on low hemoglogin")
                   )

donor_descript <- tibble(
  Variable    = c("smoking", "height", "weight", "RNF43_mutant", "prs"),
  Pretty      = c("Smoking", "Height", "Weight", "RNF43 mutant", "Polygenic risk score"),
  Type        = c("boolean", "numeric", "numeric", "boolean", "numeric"),
  Explanation = c("Does the person smoke", "Height of the donor", "Weight of the donor", 
                   "Mutation at RNF43 gene in chromosome 17 position 58358769", "Polygenic risk score for hemoglobin")
)

# Converts column names of a dataframe 'df' to pretty format using dataframe 'description'.
to_pretty <- function(df, description) {
  old_names <- colnames(df)
  new_names <- description %>% filter(Variable %in% all_of(old_names)) %>% pull(Pretty)
  colnames(df) <- new_names
  df
}

```

<!-- <h2> Initialization </h2> -->
```{r Setup, setup = TRUE, echo=FALSE, message=FALSE}

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
library(rstan)
suppressPackageStartupMessages(library(caret))
suppressPackageStartupMessages(library(tictoc))
suppressPackageStartupMessages(library(entropy))
suppressPackageStartupMessages(library(brms))
suppressPackageStartupMessages(library(ggmcmc))
suppressPackageStartupMessages(library(ggthemes))
suppressPackageStartupMessages(library(ggridges))
suppressPackageStartupMessages(library(ROCR))
suppressPackageStartupMessages(library(pROC))
suppressPackageStartupMessages(library(furrr))
suppressPackageStartupMessages(library(sn))
library(tidyselect)

knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
#knitr::opts_chunk$set(echo=TRUE, message=TRUE)
#options(warn = 1)

message("Parameters are:")
for (name in names(params)) {
  message(sprintf("%s = ", name), params[[name]])
}

# These are used to select which computations to perform,
# base on params$gender and params$method
compute_male   <- params$gender %in% c("male", "both")
compute_female <- params$gender %in% c("female", "both")
compute_decision_tree  <- params$method %in% c("decision-tree", "both")
compute_random_forest <- params$method %in% c("random-forest", "both")
compute_male_decision_tree <- compute_male && compute_decision_tree 
compute_female_decision_tree <- compute_female && compute_decision_tree
compute_male_random_forest <- compute_male && compute_random_forest
compute_female_random_forest <- compute_female && compute_random_forest

set.seed(123)
if (!is.null(params$cores)) {
  options(mc.cores = params$cores)   # This option is in package parallel
}


datadir = "../data/rdata/"
rawresultdir = "../data/raw_results/"   # I store plot objects and tables in this directory

# Id for a run. For example files in rawresultdir use this id as part of their name. 
# Probably I should add a possibility to download raw results from the web interface.
if (is.null(params$id)) {
  id <- paste(params$date, params$sample_fraction, params$hlen, params$hlen_exactly, params$extra_id, sep="_") 
} else {
  id <- params$id
}

source("helper_functions.R")
source("validate_stan_fit.R")
#source("ppc.R")


data <- load_single(params$input_file) # Forgets the name of the object

data <- data %>%
  mutate(days_to_previous_fb = as.double(days_to_previous_fb),
         donor = as.character(donor))   # For some reason this cannot be a factor



sample_fraction <- params$sample_fraction

is.wholenumber <- function(x, tol = .Machine$double.eps^0.5)  abs(x - round(x)) < tol

if (sample_fraction > 1 && is.wholenumber(sample_fraction)) {  # If a sample size is given instead of fraction, convert it to sample fraction
  low_limit <- ifelse(params$method=="no-fix", 2, 1)
  data <- data %>% group_by(donor) %>%
    filter(n() > low_limit) %>%
    ungroup()
  
  if (params$gender == "male") {
    temp <- data %>% filter(gender=="Men")
  }
  else if (params$gender == "female") {
    temp <- data %>% filter(gender=="Women")
  } else {
    temp <- data
  }
  n <- length(unique(temp$donor))  # number of donors
  rm(temp)
  sample_fraction <- sample_fraction / n
  message(sprintf("Number of donors: %i, sample_fraction: %f", n, sample_fraction))
}

# I use this to pass the "smoking", "bmi", "RNF43_mutant", "prs" to the algorithms
if (!is.null(params$donor_specific_file) && (length(params$donor_specific_file) > 0)) {
  donor_variables <- donor_descript$Variable
  pretty_donor_variables <- donor_descript$Pretty
  
  findonor_and_snip_and_prs <- load_single(params$donor_specific_file)
  data <- inner_join(data, findonor_and_snip_and_prs, by="donor")
} else {
  donor_variables = NULL
}


# Pretty names for parameters
vars <- descript %>% filter(!Variable %in% c("donor", "Hb", "Hb_first", "Hb_deferral")) %>% pull(Pretty)   # Convert to pretty names

if (!is.null(donor_variables)) {
  vars     <- c(vars, pretty_donor_variables)
}

# Make sure the columns in data are in the same order as in the vars list (only needed for stan preprocessing)
variables_in_order <- setdiff(descript$Variable, "donor")
if (!is.null(donor_variables)) {
  data <- data %>% select(all_of(variables_in_order),
                          all_of(donor_variables), everything())
} else {
  data <- data %>% select(all_of(variables_in_order), everything())
}


data.male <-
  data %>% filter(gender == "Men")
data.female <-
  data %>% filter(gender == "Women")
# Split for men and women separately, done in a complicated way, because I reuse the split_set function
data.male <- split_set(data.male, 1.0)
data.female <- split_set(data.female, 1.0)
names(data.male) <- c("general","validation")
names(data.female) <- c("general","validation")
# Small test sets
smallm <- split_set(data.male$general, sample_fraction)
smallf <- split_set(data.female$general, sample_fraction)
data.male <- smallm$train
data.female <- smallf$train
rm(smallm, smallf)


# Maybe this is not needed except for linear regression
data.male <- filter_based_on_number_of_donations(data.male, params$hlen, params$hlen_exactly)
data.female <- filter_based_on_number_of_donations(data.female, params$hlen, params$hlen_exactly)



error_rows <- list()  # This is used to construct the error table in the end
                   # It has columns Model, MAE, RMSE, AUROC, and AUPR

```



## Data description



### Variables used in prediction

```{r, echo=FALSE}
kable(descript)
kable(donor_descript)
```


```{asis, echo=compute_male}
### Summary plots of variables (male)
```

```{r Summary plots for males, echo = FALSE, eval=compute_male}
#Plot distributions for male donors


data.male2 <- data.male %>%
  filter(first_event == FALSE) %>%
  select(all_of(descript$Variable)) %>%
  mutate(Hb_deferral = as.integer(Hb_deferral),
         warm_season = as.integer(warm_season),
         previous_Hb_def = as.integer(previous_Hb_def))

pmale <- data.male2 %>%
  keep(is.numeric) %>%
  to_pretty(descript) %>%
  gather() %>%
  mutate(key = factor(key, levels=descript$Pretty))  %>% # Don't sort alphabetically
  ggplot(aes(value)) +
  facet_wrap(~ key, scales = "free") +
  geom_histogram(fill = "blue")
pmale

if (!is.null(params$donor_specific_file)) {
  male_donor_specific <- findonor_and_snip_and_prs %>%
    semi_join(data.male2, by="donor") %>%
    mutate(smoking = as.integer(smoking), RNF43_mutant = as.integer(RNF43_mutant)) %>%
    keep(is.numeric) %>%
    to_pretty(donor_descript) 
  male_donor_specific %>%
    gather() %>%
    mutate(key = factor(key, levels=donor_descript$Pretty))  %>% # Don't sort alphabetically
    ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram(fill = "blue")
}
rm(data.male2, pmale);
```



```{asis, echo=compute_female}
### Summary plots of variables (female)
```

```{r Summary plots for females, echo = FALSE, eval=compute_female}
#Plot distributions for female donors

data.female2 <- data.female %>%
  filter(first_event == FALSE) %>%
  select(all_of(descript$Variable)) %>%
  mutate(Hb_deferral = as.integer(Hb_deferral),
         warm_season = as.integer(warm_season),
         previous_Hb_def = as.integer(previous_Hb_def))

pfemale <- data.female2 %>%
          keep(is.numeric) %>%
          to_pretty(descript) %>%
          gather() %>%
          mutate(key = factor(key, levels=descript$Pretty))  %>% # Don't sort alphabetically
          ggplot(aes(value)) +
            facet_wrap(~ key, scales = "free") +
            geom_histogram(fill = "orange")

pfemale

if (!is.null(params$donor_specific_file)) {
  female_donor_specific <- findonor_and_snip_and_prs %>%
    semi_join(data.female2, by="donor") %>%
    mutate(smoking = as.integer(smoking), RNF43_mutant = as.integer(RNF43_mutant))
  female_donor_specific %>%
    keep(is.numeric) %>%
    to_pretty(donor_descript) %>%
    gather() %>%
    mutate(key = factor(key, levels=donor_descript$Pretty))  %>% # Don't sort alphabetically
    ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram(fill = "orange")
}
rm(data.female2, pfemale);
```


```{r clean up memory, echo = FALSE}
rm(data); invisible(gc())
rm(data.male, data.female); invisible(gc(reset = TRUE))
```





## Results


```{asis, echo=compute_male_decision_tree}
### Decision tree, male donors
```

```{r}
dummy_plots <- function(df) {
  result <- list()
  result$conf_matrix_plot <- create_confusion_matrix_plot(df$deferral, df$predicted_labels)
  result$roc_plot <- create_roc_new(df$deferral, df$scores)
  result$pr_plot <- create_precision_recall_new(df$deferral, df$scores)
  return(result)
}
```

```{r Decision tree male donors, results="hide", eval=compute_male_decision_tree}
# Load first datasets

n=500   # We create n random rows
df <- tibble(observed = rnorm(n, 150, 20),
             predicted = rnorm(n, 150, 20),
             deferral         = as.integer(observed < params$Hb_cutoff_male),
             predicted_labels = as.integer(predicted < params$Hb_cutoff_male),
             scores           = rnorm(n))



results_male_decision_tree <- dummy_plots(df)

results_male_decision_tree$conf_matrix_plot
results_male_decision_tree$roc_plot 
results_male_decision_tree$pr_plot


error_rows[[length(error_rows)+1]] <- list(Model="Male, decision tree", MAE=NA, RMSE=NA, 
                                           MAE2=NA, RMSE2=NA, 
                                           AUC=results_male_decision_tree$roc_plot$roc_auc, 
                                           AUPR=results_male_decision_tree$pr_plot$pr_auc)

save(results_male_decision_tree, file = paste0(rawresultdir, "raw_result_male_decision_tree_", id, ".rdata"))

# Remove unnescessary values to save memory
#if (knit == TRUE) {rm(results_male_decision_tree); invisible(gc(reset = TRUE))}

```


```{asis, echo=compute_female_decision_tree}
### Decision tree, female donors
```

```{r Decision tree female donors, results="hide", eval=compute_female_decision_tree}
# Load first datasets

n=500   # We create n random rows
df <- tibble(observed = rnorm(n, 140, 20),
             predicted = rnorm(n, 140, 20),
             deferral         = as.integer(observed < params$Hb_cutoff_female),
             predicted_labels = as.integer(predicted < params$Hb_cutoff_female),
             scores           = rnorm(n))



results_female_decision_tree <- dummy_plots(df)

results_female_decision_tree$conf_matrix_plot
results_female_decision_tree$roc_plot 
results_female_decision_tree$pr_plot


error_rows[[length(error_rows)+1]] <- list(Model="Female, decision tree", MAE=NA, RMSE=NA, 
                                           MAE2=NA, RMSE2=NA, 
                                           AUC=results_female_decision_tree$roc_plot$roc_auc, 
                                           AUPR=results_female_decision_tree$pr_plot$pr_auc)

save(results_female_decision_tree, file = paste0(rawresultdir, "raw_result_female_decision_tree", id, ".rdata"))

# Remove unnescessary values to save memory
#if (knit == TRUE) {rm(results_female_decision_tree); invisible(gc(reset = TRUE))}

```


```{asis, echo=compute_male_random_forest}
### Random forest, male donors
```


```{r Random forest male donors, results="hide", eval=compute_male_random_forest}
# Load first datasets

n=500   # We create n random rows
df <- tibble(observed = rnorm(n, 150, 20),
             predicted = rnorm(n, 150, 20),
             deferral         = as.integer(observed < params$Hb_cutoff_male),
             predicted_labels = as.integer(predicted < params$Hb_cutoff_male),
             scores           = rnorm(n))



results_male_random_forest <- dummy_plots(df)

results_male_random_forest$conf_matrix_plot
results_male_random_forest$roc_plot 
results_male_random_forest$pr_plot


error_rows[[length(error_rows)+1]] <- list(Model="Male, random forest", MAE=NA, RMSE=NA, 
                                           MAE2=NA, RMSE2=NA, 
                                           AUC=results_male_random_forest$roc_plot$roc_auc, 
                                           AUPR=results_male_random_forest$pr_plot$pr_auc)

save(results_male_random_forest, file = paste0(rawresultdir, "raw_result_male_random_forest", id, ".rdata"))

# Remove unnescessary values to save memory
#if (knit == TRUE) {rm(results_male_random_forest); invisible(gc(reset = TRUE))}

```


```{asis, echo=compute_female_random_forest}
### Random forest, female donors
```

```{r Random forest female donors, results="hide", eval=compute_female_random_forest}
# Load first datasets

n=500   # We create n random rows
df <- tibble(observed = rnorm(n, 140, 20),
             predicted = rnorm(n, 140, 20),
             deferral         = as.integer(observed < params$Hb_cutoff_female),
             predicted_labels = as.integer(predicted < params$Hb_cutoff_female),
             scores           = rnorm(n))



results_female_random_forest <- dummy_plots(df)

results_female_random_forest$conf_matrix_plot
results_female_random_forest$roc_plot 
results_female_random_forest$pr_plot


error_rows[[length(error_rows)+1]] <- list(Model="Female, random_forest", MAE=NA, RMSE=NA, 
                                           MAE2=NA, RMSE2=NA, 
                                           AUC=results_female_random_forest$roc_plot$roc_auc, 
                                           AUPR=results_female_random_forest$pr_plot$pr_auc)

save(results_female_random_forest, file = paste0(rawresultdir, "raw_result_female_random_forest", id, ".rdata"))

# Remove unnescessary values to save memory
#if (knit == TRUE) {rm(results_female_random_forest); invisible(gc(reset = TRUE))}

```


### Errors

```{r Errors}

#str(error_rows)
#df <- do.call(rbind, error_rows)
for (i in seq_along(error_rows)) {
  if (i == 1) {
    errors <- as_tibble(error_rows[[1]])
  } else {
    errors <- rbind(errors, error_rows[[i]])
  }
}  
#errors <- as_tibble(df)
errors <- errors %>% rename("MAE (g / L)" = MAE, "RMSE (g / L)" = RMSE,
                            "MAE (mmol / L)" = MAE2, "RMSE (mmol / L)" = RMSE2)

write_csv(errors, paste(rawresultdir, "errors_", id, ".csv", sep = ''))
if (!is.null(params$errors_table_file)) {
  write_csv(errors, params$errors_table_file)   # Pass the table to the web app as well
}

```

```{r}
kable(errors, digits=3, format.args = list(digits=3))
```